name = "pac-file-explained"
main = "worker.js"
compatibility_date = "2026-05-11"

routes = [
  { pattern = "pac-file-explained.dev/*", zone_name = "pac-file-explained.dev" }
]


[[rules]]
type  = "Text"
globs = ["**/*.html", "**/*.css", "**/client.js", "**/ads.txt"]